/**
 * Smoke test for the Agent-mode shipping invariant:
 *   the Hermes bridge files AND its npm runtime deps MUST be declared as
 *   Tauri bundle resources, otherwise production .app builds ship without
 *   them and every Agent session silently fails to spawn (v1.1.0 / v1.1.2
 *   regression — see the v1.1.3 hotfix that added bridge/node_modules to
 *   resources).
 *
 * Since ADR 002 (docs/adr/002-bridge-runtime-tarball.md), the npm runtime
 * deps ship as a compressed `bridge-runtime.tar.zst` + `manifest.json`
 * pair (built by `scripts/pack-bridge-runtime.mjs`) instead of a raw
 * `bridge/node_modules` tree — the raw tree broke `linuxdeploy`'s AppImage
 * packaging and made every install ~210 MB heavier.
 *
 * If any of these tests fail, the CI bundle won't have everything the
 * bridge needs under `Resources/bridge/` and `resolve_bridge_path()` /
 * `resolve_bridge_runtime_dir()` will fail at runtime in the shipped .app.
 * Don't delete these without first proving the bridge is shipped some
 * other way (e.g., embedded).
 */

import { readFileSync, existsSync } from "fs";
import { describe, it, expect } from "vitest";

const TAURI_CONF = "src-tauri/tauri.conf.json";

describe("tauri.conf.json bundle resources", () => {
  const conf = JSON.parse(readFileSync(TAURI_CONF, "utf-8"));

  it("declares hermes-claude-bridge.mjs as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    expect(Array.isArray(resources)).toBe(true);
    const hasBridge = resources.some((r) =>
      r.includes("hermes-claude-bridge.mjs"),
    );
    expect(hasBridge).toBe(true);
  });

  it("declares canUseToolHelpers.mjs as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    const hasHelpers = resources.some((r) =>
      r.includes("canUseToolHelpers.mjs"),
    );
    expect(hasHelpers).toBe(true);
  });

  it("declares the packed bridge runtime tarball as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    expect(resources).toContain("bridge/runtime/bridge-runtime.tar.zst");
  });

  it("declares the bridge runtime manifest as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    expect(resources).toContain("bridge/runtime/manifest.json");
  });

  // Regression guard: the raw `bridge/node_modules` tree is exactly what
  // ADR 002 replaced (it broke linuxdeploy's AppImage packaging). If this
  // comes back, something reverted the tarball approach.
  it("does not declare the raw bridge node_modules tree as a resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    const hasRawNodeModules = resources.some(
      (r) => r === "bridge/node_modules" || r.startsWith("bridge/node_modules/"),
    );
    expect(hasRawNodeModules).toBe(false);
  });

  // Regression coverage for v1.1.4 → v1.1.5 hotfix: when we added
  // bridgeRuntimeHelpers.mjs and the bridge started importing it,
  // the resources list wasn't updated.  Bundled installs crashed at
  // runtime with `ERR_MODULE_NOT_FOUND: bridgeRuntimeHelpers.mjs`.
  // This test scans the bridge for relative .mjs imports and asserts
  // each one is declared as a Tauri resource — every future helper
  // file the bridge imports gets caught at unit-test time.
  it("every relative .mjs import in the bridge is declared as a bundle resource", () => {
    const bridgeSource = readFileSync(
      "src-tauri/bridge/hermes-claude-bridge.mjs",
      "utf-8",
    );
    // Match `from "./X.mjs"` or `from './X.mjs'`
    const importRe = /from\s+["']\.\/([^"']+\.mjs)["']/g;
    const imports = new Set<string>();
    let m: RegExpExecArray | null;
    while ((m = importRe.exec(bridgeSource)) !== null) {
      imports.add(m[1]);
    }
    expect(imports.size, "bridge should import at least one helper").toBeGreaterThan(0);

    const resources: string[] = conf?.bundle?.resources ?? [];
    for (const file of imports) {
      const expected = `bridge/${file}`;
      const found = resources.some((r) => r === expected);
      expect(
        found,
        `bridge imports './${file}' but tauri.conf.json doesn't declare '${expected}' as a resource — bundled install will crash at runtime`,
      ).toBe(true);
    }
  });

  it("every static (non-generated) bridge resource exists on disk", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    for (const r of resources) {
      // Generated by `npm run prepare:bridge` (stage-bridge-deps.mjs then
      // pack-bridge-runtime.mjs); skip the existence check so this test
      // works pre-build (CI runs unit tests before staging).
      if (r.startsWith("bridge/runtime/")) continue;
      const onDisk = `src-tauri/${r}`;
      expect(existsSync(onDisk), `expected ${onDisk} to exist`).toBe(true);
    }
  });

  // ADR 002: bridge/package.json is no longer meaningful on disk once the
  // SDK is extracted from the tarball at runtime (the extracted manifest
  // carries the version info the bridge actually reads).
  it("does not declare bridge/package.json as a resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    expect(resources).not.toContain("bridge/package.json");
  });

  it("triggers prepare:bridge as part of beforeBuildCommand", () => {
    // Without this the staged node_modules dir is missing whenever Tauri
    // builds the .app — the bug this whole pipeline exists to prevent.
    const cmd: string = conf?.build?.beforeBuildCommand ?? "";
    expect(cmd).toMatch(/prepare:bridge/);
  });
});

describe("bridge runtime package.json", () => {
  const root = JSON.parse(readFileSync("package.json", "utf-8"));
  const bridge = JSON.parse(
    readFileSync("src-tauri/bridge/package.json", "utf-8"),
  );

  it("pins the same Claude Agent SDK version as the root project", () => {
    const rootRange: string = root.dependencies["@anthropic-ai/claude-agent-sdk"];
    const bridgePin: string = bridge.dependencies["@anthropic-ai/claude-agent-sdk"];
    // Root uses a caret range (e.g. "^0.2.132"); the bridge pins the
    // exact base version so the bundled binary matches what is installed
    // in CI.  When you bump the SDK in root, also bump the bridge here.
    const rootBase = rootRange.replace(/^[\^~]/, "");
    expect(bridgePin).toBe(rootBase);
  });

  it("includes zod (peer dep of the SDK) so the bridge's dynamic `import('zod')` resolves", () => {
    expect(bridge.dependencies?.zod).toBeTruthy();
  });
});
